import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.geistMono}`}>{children}</body>
    </html>
  );
}
